### ISSUE TITLE
AttributeError: 'TreebankWordTokenizer' object has no attribute 'STARTING_QUOTES'

### ISSUE THREAD

**Issue by kristiank** [alvations/pywsd#39]
After installing pywsd with the command `pip3 install --user pywsd` I get the following error when importing the module in python3.

```python3
>>> from pywsd.similarity import max_similarity
Warming up PyWSD (takes ~10 secs)... Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anon/.local/lib/python3.6/site-packages/pywsd/__init__.py", line 19, in <module>
    import pywsd.lesk
  File "/home/anon/.local/lib/python3.6/site-packages/pywsd/lesk.py", line 19, in <module>
    from pywsd.utils import word_tokenize
  File "/home/anon/.local/lib/python3.6/site-packages/pywsd/utils.py", line 20, in <module>
    _treebank_word_tokenizer.STARTING_QUOTES.insert(0, (improved_open_quote_regex, r' \1 '))
AttributeError: 'TreebankWordTokenizer' object has no attribute 'STARTING_QUOTES'
```

**Comment by alvations** [comment]
Upgrading the `pywsd` should automatically upgrade your NLTK version which would resolve the problem.

```
pip install -U --user pywsd
```

The `-U` option is to upgrade.

**Comment by kristiank** [comment]
Thanks, now it works!
